using System.ComponentModel;

namespace PTUDatabase
{
    public enum OtherCapability
    {
        Alluring,
        [Description("Alluring (only in Rain)")]
        AlluringInRain,
        Amorphous,
        AsOne,
        AuraReader,
        AuraPulse,
        Blindsense,
        Bloom,
        Blender,
        Chilled,
        Confined,
        Darkvision,
        DeadSilent,
        DeltaEvolver,
        DreamMist,
        DreamReader,
        EggWarmer,
        Firestarter,
        FormeChange,
        Fortune,
        Fountain,
        Freezer,
        Gardener,
        GatherUnown,
        Gilled,
        Glow,
        Groundshaper,
        Guster,
        HeartGift,
        Heater,
        HerbGrowth,
        HoneyGather,
        Illusionist,
        Inflatable,
        Invisibility,
        Juicer,
        KeystoneWarp,
        LeafCrafter,
        LetterPress,
        LivingWeapon,
        Magnetic,
        Marsupial,
        Materializer,
        MilkCollection,
        MindLock,
        Multiform,
        MushroomHarvest,
        OriginForme,
        PackMon,
        PearlCreation,
        Phasing,
        Planter,
        [Description("Planter (Berries)")]
        PlanterBerries,
        [Description("Planter (Herbs)")]
        PlanterHerbs,
        Premonition,
        Reach,
        ShadowMeld,
        Shapeshifter,
        Shrinkable,
        SkyForme,
        Soulless,
        SplitEvolution,
        Sprouter,
        Stealth,
        StickyHold, // Changed from an Ability to a Capability?
        Telekinetic,
        Telepath,
        Threaded,
        Tracker,
        Tremorsense,
        Underdog,
        ViralFusion,
        VolatileBomb,
        Wallclimber,
        WeaponBond,
        Weathershape,
        Wielder,
        Wired,
        [Description("X-Ray Vision")]
        XRayVision,
        Zapper,
        ZygardeCells,
    }
}

